# Generated by Django 6.0.7 on 2026-07-07 14:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('prazo_offset_dias', models.PositiveIntegerField(default=0, help_text='Dia do mês de referência que é o prazo-limite desta fase. Ex.: 10 = dia 10.', verbose_name='Prazo (dia do mês)')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['modelo', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ModeloChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Modelo de checklist',
                'verbose_name_plural': 'Modelos de checklist',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão social')),
                ('cnpj', models.CharField(blank=True, max_length=20, unique=True, verbose_name='CNPJ')),
                ('ativa', models.BooleanField(default=True, help_text='Empresas inativas não entram em novos ciclos.')),
                ('equipe', models.ForeignKey(blank=True, help_text='Equipe que assume esta empresa por padrão a cada ciclo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='fechamento.equipe', verbose_name='Equipe padrão')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fechamento.fase')),
            ],
            options={
                'verbose_name': 'Item do checklist',
                'verbose_name_plural': 'Itens do checklist',
                'ordering': ['fase', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='fase',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='fechamento.modelochecklist'),
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(help_text='Ex.: 2026-06', max_length=7, verbose_name='Referência (AAAA-MM)')),
                ('data_referencia', models.DateField(help_text='Primeiro dia do mês. Ex.: 2026-06-01', verbose_name='Início do mês de referência')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('concluido', 'Concluído')], default='aberto', max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos', to='fechamento.modelochecklist')),
            ],
            options={
                'verbose_name': 'Ciclo de fechamento',
                'verbose_name_plural': 'Ciclos de fechamento',
                'ordering': ['-data_referencia'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='fechamento.ciclo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='fechamento.empresa')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fechamento.equipe')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['empresa__razao_social'],
            },
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('feito', 'Feito'), ('na', 'N/A')], default='pendente', max_length=20)),
                ('data', models.DateField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='fechamento.item')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_atualizados', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_status', to='fechamento.processo')),
            ],
            options={
                'verbose_name': 'Status de item',
                'verbose_name_plural': 'Status de itens',
                'ordering': ['item__fase__ordem', 'item__ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='ciclo',
            constraint=models.UniqueConstraint(fields=('modelo', 'referencia'), name='uniq_ciclo_modelo_ref'),
        ),
        migrations.AddConstraint(
            model_name='processo',
            constraint=models.UniqueConstraint(fields=('ciclo', 'empresa'), name='uniq_processo_ciclo_empresa'),
        ),
        migrations.AddConstraint(
            model_name='itemstatus',
            constraint=models.UniqueConstraint(fields=('processo', 'item'), name='uniq_itemstatus_processo_item'),
        ),
    ]
