# Generated by Django 6.0.7 on 2026-07-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj', ''), _negated=True), fields=('cnpj',), name='uniq_empresa_cnpj'),
        ),
    ]
