# Generated by Django 6.0.7 on 2026-07-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0003_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão social')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Empresa (catálogo)',
                'verbose_name_plural': 'Catálogo de empresas',
                'ordering': ['razao_social'],
            },
        ),
    ]
