# Generated by Django 6.0.7 on 2026-07-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0004_catalogoempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pontua',
            field=models.BooleanField(default=True, help_text="Desmarque para itens preliminares (ex.: 'Solicitado') que não entram no cálculo de %.", verbose_name='Conta no progresso'),
        ),
        migrations.AlterField(
            model_name='itemstatus',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('feito', 'Feito'), ('manual', 'Manual'), ('na', 'N/A')], default='pendente', max_length=20),
        ),
    ]
