# Generated by Django 6.0.7 on 2026-07-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0005_item_pontua_alter_itemstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='equipes',
            field=models.ManyToManyField(blank=True, help_text='Equipes que usam este detalhamento (só para fases não-principais).', related_name='fases_detalhe', to='fechamento.equipe'),
        ),
        migrations.AddField(
            model_name='fase',
            name='principal',
            field=models.BooleanField(default=True, help_text='Fases principais contam no % geral e valem para todas as equipes. Desmarque para checklists de detalhamento (opcionais por equipe).'),
        ),
    ]
