# Generated by Django 6.0.7 on 2026-07-07 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0006_fase_equipes_fase_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='data_referencia',
            field=models.DateField(help_text='Ex.: 2026-02-01', verbose_name='Primeiro dia da competência'),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='referencia',
            field=models.CharField(help_text='Mês contábil sendo fechado. Ex.: 2026-02 (o trabalho ocorre no mês seguinte).', max_length=7, verbose_name='Competência (AAAA-MM)'),
        ),
        migrations.AlterField(
            model_name='fase',
            name='prazo_offset_dias',
            field=models.PositiveIntegerField(default=0, help_text='Dia do mês de trabalho usado como sugestão inicial do prazo ao abrir um ciclo. O prazo real é definido por ciclo.', verbose_name='Dia sugerido do prazo'),
        ),
        migrations.CreateModel(
            name='CicloPrazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_limite', models.DateField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='fechamento.ciclo')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prazos_ciclo', to='fechamento.fase')),
            ],
            options={
                'verbose_name': 'Prazo do ciclo',
                'verbose_name_plural': 'Prazos do ciclo',
                'ordering': ['fase__ordem'],
                'constraints': [models.UniqueConstraint(fields=('ciclo', 'fase'), name='uniq_cicloprazo_ciclo_fase')],
            },
        ),
    ]
