# Generated by Django 6.0.7 on 2026-07-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0007_alter_ciclo_data_referencia_alter_ciclo_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fase',
            name='equipes',
        ),
        migrations.AddField(
            model_name='fase',
            name='empresas',
            field=models.ManyToManyField(blank=True, help_text='Empresas que usam este detalhamento (só para fases não-principais). Escolhido empresa por empresa — independe da equipe.', related_name='fases_detalhe', to='fechamento.empresa'),
        ),
        migrations.AlterField(
            model_name='fase',
            name='principal',
            field=models.BooleanField(default=True, help_text='Fases principais contam no % geral e valem para todas as empresas. Desmarque para checklists de detalhamento (opcionais por empresa).'),
        ),
    ]
