# Generated by Django 6.0.7 on 2026-07-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0008_remove_fase_equipes_fase_empresas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='equipes',
            field=models.ManyToManyField(blank=True, help_text='Equipes que este usuário atende. Operador só vê as empresas dessas equipes.', related_name='membros', to='fechamento.equipe'),
        ),
    ]
