# Generated by Django 6.0.7 on 2026-07-14 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0009_perfil_equipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorCeipim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveSmallIntegerField(help_text='0 = indicador anual (coluna do ano anterior); 1-12 = mês específico.', verbose_name='Mês')),
                ('status', models.CharField(choices=[('na', 'N/A'), ('previa', 'Prévia'), ('retificado', 'Retificado'), ('definitivo', 'Definitivo')], default='na', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_ceipim', to='fechamento.empresa')),
            ],
            options={
                'verbose_name': 'Indicador CEIPIM',
                'verbose_name_plural': 'Indicadores CEIPIM',
                'ordering': ['empresa__razao_social', 'ano', 'mes'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'ano', 'mes'), name='uniq_ceipim_empresa_ano_mes')],
            },
        ),
    ]
