# Generated by Django 6.0.7 on 2026-07-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0010_indicadorceipim'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='participa_ceipim',
            field=models.BooleanField(default=False, help_text='Entra na lista de Indicadores CEIPIM (função independente dos ciclos).', verbose_name='Participa do CEIPIM'),
        ),
    ]
