# Generated by Django 6.0.7 on 2026-07-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0012_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de admissão'),
        ),
    ]
