# Generated by Django 6.0.7 on 2026-07-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0013_perfil_cargo_perfil_data_admissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=64, unique=True, verbose_name='Identificador do ticket')),
                ('usuario', models.CharField(max_length=150)),
                ('usado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ticket do portal',
                'verbose_name_plural': 'Tickets do portal',
                'ordering': ['-usado_em'],
            },
        ),
    ]
