# Generated by Django 6.0.7 on 2026-07-21 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0014_ticketportal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='participa_lucro_real',
            field=models.BooleanField(default=False, help_text='Entra no acompanhamento de Clientes Lucro Real (função independente dos ciclos).', verbose_name='Cliente Lucro Real'),
        ),
        migrations.CreateModel(
            name='AcompanhamentoLucroReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição na tabela (a coluna SEQUÊNCIA da planilha).', verbose_name='Sequência')),
                ('apuracao', models.CharField(choices=[('na', 'N/A'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('receita_bruta', 'Receita bruta')], default='na', max_length=20, verbose_name='Apuração')),
                ('atualizacoes', models.CharField(blank=True, help_text="O que falta / quem está trabalhando. Ex.: 'FALTA O CUSTO'.", max_length=255, verbose_name='Atualizações')),
                ('previsao_entrega', models.DateField(blank=True, null=True, verbose_name='Previsão de entrega')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lucro_real', to='fechamento.empresa')),
            ],
            options={
                'verbose_name': 'Cliente Lucro Real',
                'verbose_name_plural': 'Clientes Lucro Real',
                'ordering': ['ordem', 'empresa__razao_social'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'ano'), name='uniq_lucroreal_empresa_ano')],
            },
        ),
    ]
