# Generated by Django 6.0.7 on 2026-07-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0015_empresa_participa_lucro_real_acompanhamentolucroreal'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamentolucroreal',
            name='status_t1',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('na', 'N/A')], default='pendente', max_length=20, verbose_name='1º trimestre'),
        ),
        migrations.AddField(
            model_name='acompanhamentolucroreal',
            name='status_t2',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('na', 'N/A')], default='pendente', max_length=20, verbose_name='2º trimestre'),
        ),
        migrations.AddField(
            model_name='acompanhamentolucroreal',
            name='status_t3',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('na', 'N/A')], default='pendente', max_length=20, verbose_name='3º trimestre'),
        ),
        migrations.AddField(
            model_name='acompanhamentolucroreal',
            name='status_t4',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('na', 'N/A')], default='pendente', max_length=20, verbose_name='4º trimestre'),
        ),
    ]
