# Generated by Django 6.0.7 on 2026-07-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0016_acompanhamentolucroreal_status_t1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamentolucroreal',
            name='status_geral',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('na', 'N/A')], default='pendente', help_text='Usado quando a apuração não é trimestral — aí os quatro trimestres não fazem sentido e a empresa tem uma situação só.', max_length=20, verbose_name='Situação'),
        ),
    ]
