# Generated by Django 6.0.7 on 2026-08-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0017_acompanhamentolucroreal_status_geral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstatus',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aguardando', 'Aguardando'), ('feito', 'Feito'), ('manual', 'Manual'), ('na', 'N/A')], default='pendente', max_length=20),
        ),
    ]
